import sys
import io
import code
import logging
import traceback
from typing import Dict, Any, List

logger = logging.getLogger(__name__)

class RecursiveREPL:
    """
    A cooperative Python sandbox for the RLM.
    Executes code generated by Qwen 3 in a restricted environment.
    """
    def __init__(self, tools_instance: Any, context_variables: Dict[str, Any] = None):
        """
        Args:
            tools_instance: Instance of SafeTools.
            context_variables: Dict of variables to expose (e.g., PROMPT_CONTEXT).
        """
        self.tools = tools_instance
        self.context_variables = context_variables or {}
        
        # Define the Safe Locals (The Sandbox)
        self.safe_locals = {
            "tools": self.tools,
            "__builtins__": self._get_safe_builtins(),
            **self.context_variables
        }
        
        # The interpreter
        self.interpreter = code.InteractiveInterpreter(self.safe_locals)

    def _get_safe_builtins(self):
        """
        Explicitly whitelists safe built-in functions.
        Removes open, __import__, eval, exec, etc.
        """
        whitelist = {
            # Basic Types
            "True": True, "False": False, "None": None,
            "str": str, "int": int, "float": float, "bool": bool,
            "list": list, "dict": dict, "set": set, "tuple": tuple,
            "len": len, "range": range, "enumerate": enumerate,
            # Math
            "min": min, "max": max, "sum": sum, "abs": abs, "round": round,
            # String ops
            "print": print, # mapped to captured stdout later? 
                            # Actually code.InteractiveInterpreter uses sys.stdout, 
                            # so we don't need to remap print if we capture sys.stdout.
            "format": format, "repr": repr,
            # Iterators
            "zip": zip, "map": map, "filter": filter, "sorted": sorted,
            # Exceptions
            "Exception": Exception, "ValueError": ValueError, "TypeError": TypeError
        }
        return whitelist

    def execute(self, code_block: str) -> str:
        """
        Executes a block of Python code and captures the output.
        Returns the STDOUT + Final Expression Value.
        """
        # Capture STDOUT
        old_stdout = sys.stdout
        redirected_output = io.StringIO()
        sys.stdout = redirected_output
        
        result_msg = ""
        
        try:
            # 1. Compile to check for syntax errors
            # We strip whitespace to avoid indentation errors if LLM messed up
            code_block = code_block.strip()
            
            # code.InteractiveInterpreter.runsource runs ONE statement.
            # We want to run a script. 'exec' style.
            # But we are using InteractiveInterpreter to maintain state if we wanted (we don't persist state between turns yet).
            # Actually, `exec()` logic on `safe_locals` is easier for a script block.
            # InteractiveInterpreter is useful for line-by-line REPL. 
            # RLM usually sends a full chunk.
            
            # Let's use Restricted Execution via exec() with our safe_locals
            # This is "Cooperative Safety".
            
            exec(code_block, self.safe_locals)
            
            # If the code block is just an expression (e.g. "tools.get_time()"), 'exec' prints nothing.
            # We want to emulate REPL behavior where the last line is printed if it's an expression.
            # However, detecting that is hard. We'll rely on explicit `print()` or saving to variables for now.
            # Or we can AST parse the last line. 
            # For Phase 1, let's keep it simple: Qwen must `print()`.
            
        except Exception:
            # Print traceback to the capture buffer
            traceback.print_exc(file=redirected_output)
        finally:
            # Restore STDOUT
            sys.stdout = old_stdout
            
        output = redirected_output.getvalue()
        
        if not output:
            return "[System: Code executed successfully, but produced no output. Did you forget to print()?]"
            
        return output.strip()
